#!/usr/bin/env python3
"""Structure check for this repo (MODULE SOP section 9.1), plus generation of MODULE_MAP.md and .sop/function_index.json.

Usage: tools/sop_check.py [--write] [REPO_ROOT]
  default  check only; exit 1 on any failure (a stale generated file is a failure)
  --write  regenerate MODULE_MAP.md and .sop/function_index.json first, then check
"""
import ast
import json
import os
import sys
import tomllib

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from doc_check import card_findings  # noqa: E402

CARD_SECTIONS = ['Purpose', 'Owns', 'Does Not Own', 'Public Interface', 'Depends On', 'Invariants',
                 'Test Locations', 'Known Gotchas']
CODE_EXT = ('.py', '.sh')


def load_registry(root):
    """Return the parsed modules.toml."""
    with open(os.path.join(root, 'modules.toml'), 'rb') as f:
        return tomllib.load(f)


def _module_map(reg):
    """Return the generated MODULE_MAP.md text (one line per module, registry order)."""
    lines = ['# MODULE MAP (generated by tools/sop_check.py --write; never hand-edit)', '']
    for name, m in reg['modules'].items():
        deps = ', '.join(m.get('depends_on', [])) or 'none'
        lines.append(f"- **{name}** `{m['path']}` - owns: {m['owns']} | depends on: {deps} | card: `{m['card']}`")
    return '\n'.join(lines) + '\n'


def _function_index(root, reg):
    """Return the function index (public functions/classes of every code module), sorted, as a JSON string."""
    out = []
    for name, m in reg['modules'].items():
        base = os.path.join(root, m['path'])
        for fn in sorted(os.listdir(base)):
            if not fn.endswith('.py'):
                continue
            tree = ast.parse(open(os.path.join(base, fn)).read())
            for node in tree.body:
                if isinstance(node, (ast.FunctionDef, ast.ClassDef)) and not node.name.startswith('_'):
                    sig = ''
                    if isinstance(node, ast.FunctionDef):
                        sig = '(' + ', '.join(a.arg for a in node.args.args) + ')'
                    out.append({'module': name, 'name': node.name, 'signature': sig,
                                'doc': (ast.get_docstring(node) or '').split('\n')[0],
                                'file': f"{m['path']}/{fn}", 'line': node.lineno})
    return json.dumps(out, indent=1) + '\n'


def check(root, write=False):
    """Run every structure check. Returns (failures, warnings) as lists of strings."""
    fails, warns = [], []
    reg = load_registry(root)
    proj, mods = reg['project'], reg['modules']
    registered = {m['path'] for m in mods.values()}
    skip = set(proj.get('non_module_dirs', [])) | {'.git'}
    # 1. registry <-> folders, both directions (top level, and one level down inside registered modules)
    for p in registered:
        if not os.path.isdir(os.path.join(root, p)):
            fails.append(f'registry path does not exist: {p}')
    for d in sorted(os.listdir(root)):
        if os.path.isdir(os.path.join(root, d)) and d not in skip and d not in registered:
            fails.append(f'unregistered folder: {d}')
    for p in sorted(registered):
        full = os.path.join(root, p)
        for d in sorted(os.listdir(full)) if os.path.isdir(full) else []:
            sub = f'{p}/{d}'
            if os.path.isdir(os.path.join(full, d)) and d not in ('references', '__pycache__') and sub not in registered:
                fails.append(f'unregistered sub-folder: {sub}')
    # 1b. nesting: a registered module inside another registered module's folder is a sub-module (any depth),
    #     so its depends_on must name its direct parent, the nearest registered ancestor folder
    by_path = {m['path']: n for n, m in mods.items()}
    for name, m in mods.items():
        parts = m['path'].split('/')
        for i in range(len(parts) - 1, 0, -1):
            parent = by_path.get('/'.join(parts[:i]))
            if parent:
                if parent not in m.get('depends_on', []):
                    fails.append(f'{name}: sub-module of {parent}, but depends_on does not name its parent')
                break
    # 2. every module card exists with every required section
    for name, m in mods.items():
        card = os.path.join(root, m['card'])
        if not os.path.isfile(card):
            fails.append(f'{name}: card missing: {m["card"]}')
            continue
        text = open(card).read()
        for s in CARD_SECTIONS:
            if f'\n## {s}\n' not in '\n' + text:
                fails.append(f'{name}: card section missing: ## {s}')
        for dep in m.get('depends_on', []):
            if dep not in mods:
                fails.append(f'{name}: depends_on unknown module {dep}')
    # 2b. module docs: README present, card matches registry and code, parent README names its sub-modules
    fails.extend(card_findings(root, reg))
    # 3. line caps on code (modules may be exempt only via line_cap_exempt, which needs an ADR)
    for name, m in mods.items():
        if m.get('line_cap_exempt'):
            continue
        for dp, _dn, files in os.walk(os.path.join(root, m['path'])):
            for fn in files:
                if fn.endswith(CODE_EXT):
                    n = sum(1 for _ in open(os.path.join(dp, fn)))
                    rel = os.path.relpath(os.path.join(dp, fn), root)
                    if n > proj['line_cap_hard']:
                        fails.append(f'{rel}: {n} lines > hard cap {proj["line_cap_hard"]}')
                    elif n > proj['line_cap_soft']:
                        warns.append(f'{rel}: {n} lines > soft cap {proj["line_cap_soft"]}')
    # 4. architecture doc word budget
    words = len(open(os.path.join(root, 'ARCHITECTURE.md')).read().split())
    if words > proj['architecture_word_budget']:
        fails.append(f'ARCHITECTURE.md: {words} words > budget {proj["architecture_word_budget"]}')
    # 5. import contract: code in a module may import only its own files (stdlib otherwise)
    local = {n: {fn[:-3] for fn in os.listdir(os.path.join(root, m['path'])) if fn.endswith('.py')} for n, m in mods.items()}
    for name, m in mods.items():
        for fn in local[name]:
            tree = ast.parse(open(os.path.join(root, m['path'], fn + '.py')).read())
            for node in ast.walk(tree):
                if isinstance(node, ast.Import):
                    names = [a.name for a in node.names]
                elif isinstance(node, ast.ImportFrom):
                    if node.module:
                        names = [node.module]
                    elif node.level:
                        # `from . import x`: x names the sibling module — the dependency.
                        names = [a.name.split('.')[0] for a in node.names if a.name != '*']
                    else:
                        names = []
                else:
                    names = []
                for imp in names:
                    for other, files in local.items():
                        if other != name and other not in m.get('depends_on', []) and imp.split('.')[0] in files:
                            fails.append(f'{m["path"]}/{fn}.py imports {imp} from module {other} (not in depends_on)')
    # 6. generated files are fresh
    gen = {'MODULE_MAP.md': _module_map(reg), os.path.join('.sop', 'function_index.json'): _function_index(root, reg)}
    for rel, want in gen.items():
        path = os.path.join(root, rel)
        if write:
            os.makedirs(os.path.dirname(path) or root, exist_ok=True)
            open(path, 'w').write(want)
        elif not os.path.isfile(path) or open(path).read() != want:
            fails.append(f'{rel} is stale or missing (run tools/sop_check.py --write)')
    return fails, warns


if __name__ == '__main__':
    args = [a for a in sys.argv[1:] if a != '--write']
    repo = args[0] if args else os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    f, w = check(repo, write='--write' in sys.argv)
    for x in w:
        print('WARN', x)
    for x in f:
        print('FAIL', x)
    print('RESULT', 'PASS' if not f else f'FAIL ({len(f)})')
    sys.exit(1 if f else 0)
